// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9qdAhE88XOem2C5bAsWH2IZctjyG3BMY',
    appId: '1:1031538557629:web:44b2f0092decd1c04eadd4',
    messagingSenderId: '1031538557629',
    projectId: 'recogida-aceite',
    authDomain: 'recogida-aceite.firebaseapp.com',
    storageBucket: 'recogida-aceite.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDkhCONAuholBhuHDlZHPdRotozo5_iBs',
    appId: '1:1031538557629:android:49fc3c453408e1054eadd4',
    messagingSenderId: '1031538557629',
    projectId: 'recogida-aceite',
    storageBucket: 'recogida-aceite.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd8Ceaj8r9mHgZIriDs1eEOb0PrEDGqoM',
    appId: '1:1031538557629:ios:7eece9dfb32a42e44eadd4',
    messagingSenderId: '1031538557629',
    projectId: 'recogida-aceite',
    storageBucket: 'recogida-aceite.firebasestorage.app',
    iosBundleId: 'com.example.appRecogidaAceite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd8Ceaj8r9mHgZIriDs1eEOb0PrEDGqoM',
    appId: '1:1031538557629:ios:7eece9dfb32a42e44eadd4',
    messagingSenderId: '1031538557629',
    projectId: 'recogida-aceite',
    storageBucket: 'recogida-aceite.firebasestorage.app',
    iosBundleId: 'com.example.appRecogidaAceite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9qdAhE88XOem2C5bAsWH2IZctjyG3BMY',
    appId: '1:1031538557629:web:9541d36e0b57f27e4eadd4',
    messagingSenderId: '1031538557629',
    projectId: 'recogida-aceite',
    authDomain: 'recogida-aceite.firebaseapp.com',
    storageBucket: 'recogida-aceite.firebasestorage.app',
  );
}
